# Generated by Django 6.0.4 on 2026-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contactinfo_address_remove_contactinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='slug',
            field=models.SlugField(default='facebook', verbose_name='Код (facebook, instagram)'),
            preserve_default=False,
        ),
    ]
