# Generated by Django 6.0.4 on 2026-04-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_sociallink_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='map_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='street',
            field=models.CharField(default='-', max_length=150, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Полный адрес'),
        ),
    ]
