# Generated by Django 6.0.4 on 2026-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactaddress_map_url_contactaddress_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddress',
            name='map_url',
            field=models.TextField(blank=True, verbose_name='Ссылка на карту'),
        ),
    ]
