# Generated by Django 6.0.4 on 2026-04-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contactaddress_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон магазина'),
        ),
    ]
