# Generated by Django 6.0.4 on 2026-04-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название языка')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код языка')),
                ('flag', models.CharField(blank=True, max_length=10, verbose_name='Флаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['sort', 'name'],
            },
        ),
    ]
